### ISSUE TITLE
Support `discriminator` in openapi generator

### ISSUE THREAD

**Issue by fabien0102** [contiamo/restful-react#156]
**Is your feature request related to a problem? Please describe.**

We actually don't deal with the `discrimator` pattern, the actual workaround is to use `oneOf` combine with `enum` like this:

```yaml
Error:
  oneOf:
  - "$ref": "#/components/schemas/GeneralError"
  - "$ref": "#/components/schemas/FieldError"
GeneralError:
  type: object
  required:
  - type
  - message
  properties:
    type:
      type: string
      enum:
      - GeneralError
    message:
      type: string
FieldError:
  type: object
  required:
  - type
  - message
  - key
  properties:
    type:
      type: string
      enum:
      - FieldError
    message:
      type: string
    key:
      type: string
```

**Describe the solution you'd like**
The goal is to support the discrimator pattern as describe here -> https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

The previous example will become:

```yaml
Error:
  oneOf:
  - "$ref": "#/components/schemas/GeneralError"
  - "$ref": "#/components/schemas/FieldError"
  discriminator:
    propertyName: type
    mapping:
      GeneralError: "#/components/schemas/GeneralError"
      FieldError: "#/components/schemas/FieldError"
GeneralError:
  type: object
  required:
  - type
  - message
  properties:
    type:
      type: string
    message:
      type: string
FieldError:
  type: object
  required:
  - type
  - message
  - key
  properties:
    type:
      type: string
    message:
      type: string
    key:
      type: string

```

The generated types for the two previous examples should be the same:

```ts
export interface GeneralError {
  type: "GeneralError";
  message: string;
}

export interface FieldError {
  type: "FieldError";
  message: string;
  key: string;
}

export type Error = GeneralError | FieldError;
```
